<template>
  <ion-page class="login-page"><ion-content :fullscreen="true" class="ion-padding"><main class="login-shell"><section class="login-intro"><p class="eyebrow">SMART SALE</p><h1>让门店经营更轻一点。</h1><p>一个账号管理商品、销售和顾客扫码售前服务。</p></section><form class="login-form" @submit.prevent="submit"><div class="auth-switch" role="tablist"><button type="button" :class="{ active: mode === 'login' }" @click="mode = 'login'">登录</button><button type="button" :class="{ active: mode === 'signup' }" @click="mode = 'signup'">创建门店</button></div><ion-item><ion-input v-model="email" type="email" label="邮箱" label-placement="stacked" autocomplete="email" required /></ion-item><ion-item><ion-input v-model="password" type="password" label="密码" label-placement="stacked" :autocomplete="mode === 'login' ? 'current-password' : 'new-password'" :minlength="8" required /></ion-item><ion-note v-if="error" color="danger" class="auth-error">{{ error }}</ion-note><ion-button type="submit" expand="block" :disabled="submitting">{{ submitting ? '处理中…' : mode === 'login' ? '登录后台' : '创建账号' }}</ion-button><button v-if="mode === 'login'" type="button" class="text-button" @click="sendReset">忘记密码</button><ion-note color="medium" class="auth-hint">{{ mode === 'login' ? '登录后即可继续管理已有门店。' : '创建账号后，按向导填写门店资料即可生成专属二维码。' }}</ion-note></form></main></ion-content></ion-page>
</template>
<script setup lang="ts">
import { ref } from 'vue'; import { useRouter, useRoute } from 'vue-router'; import { IonPage, IonContent, IonItem, IonInput, IonButton, IonNote } from '@ionic/vue'; import { useAuth } from '@/composables/useAuth'; import { showToast } from '@/composables/useToast';
const router=useRouter(); const route=useRoute(); const {signIn,signUp,resetPassword}=useAuth(); const email=ref(''); const password=ref(''); const error=ref(''); const submitting=ref(false); const mode=ref<'login'|'signup'>('login');
async function submit(){submitting.value=true; error.value=''; try {if(mode.value==='signup'){const signedIn=await signUp(email.value.trim(),password.value);if(!signedIn){await showToast('注册成功，请先到邮箱完成验证后再登录','success');mode.value='login';return;}await router.replace('/onboarding');return;}await signIn(email.value.trim(),password.value);await router.replace(typeof route.query.redirect==='string'?route.query.redirect:'/tabs/home');}catch(e){error.value=e instanceof Error?e.message:'操作失败，请稍后重试';}finally{submitting.value=false;}}
async function sendReset(){if(!email.value.trim()){error.value='请先填写注册邮箱';return;}try{await resetPassword(email.value.trim());await showToast('重置邮件已发送，请查收邮箱','success');}catch(e){error.value=e instanceof Error?e.message:'邮件发送失败';}}
</script>
