<template>
  <ion-page><ion-header translucent><ion-toolbar><ion-buttons slot="start"><ion-back-button default-href="/tabs/more" /></ion-buttons><ion-title>店铺与 AI 设置</ion-title></ion-toolbar></ion-header><ion-content :fullscreen="true" class="ion-padding">
    <ion-card><ion-card-header><ion-card-title>店铺资料</ion-card-title></ion-card-header><ion-card-content><ion-item><ion-label position="stacked">店铺名称</ion-label><ion-input v-model="profile.name" /></ion-item><ion-item><ion-label position="stacked">地址</ion-label><ion-input v-model="profile.address" /></ion-item><ion-item><ion-label position="stacked">联系电话</ion-label><ion-input v-model="profile.phone" /></ion-item><ion-item><ion-label position="stacked">营业时间</ion-label><ion-input v-model="profile.hours" placeholder="08:00-21:00" /></ion-item><ion-item><ion-label position="stacked">买家端欢迎语</ion-label><ion-textarea v-model="profile.welcome" :rows="2" /></ion-item><ion-button expand="block" class="ion-margin-top" @click="saveProfileHandler">保存店铺资料</ion-button></ion-card-content></ion-card>
    <ion-card><ion-card-header><ion-card-title>AI 服务</ion-card-title><ion-card-subtitle>模型密钥由 Supabase Edge Function Secrets 管理</ion-card-subtitle></ion-card-header><ion-card-content><ion-item><ion-label position="stacked">平台</ion-label><ion-select v-model="llm.provider" interface="popover"><ion-select-option value="deepseek">DeepSeek</ion-select-option><ion-select-option value="openai-compatible">OpenAI-compatible</ion-select-option></ion-select></ion-item><ion-item><ion-label position="stacked">模型</ion-label><ion-input v-model="llm.model" placeholder="deepseek-chat" /></ion-item><ion-item><ion-label position="stacked">服务地址（可选）</ion-label><ion-input v-model="llm.baseUrl" placeholder="https://api.deepseek.com" /></ion-item><ion-button expand="block" class="ion-margin-top" @click="saveLlmHandler">保存模型偏好</ion-button><ion-note color="medium" class="ion-padding-top block-note">供应商 Key、Embedding 配置和 service role 密钥只能在 Supabase Secrets 中配置，浏览器不会保存或发送 Key。</ion-note></ion-card-content></ion-card>
    <ion-card><ion-card-header><ion-card-title>生产知识库</ion-card-title><ion-card-subtitle>支持 PDF、DOCX、TXT、Markdown，上传后会进入草稿审核。</ion-card-subtitle></ion-card-header><ion-card-content><ion-note color="medium" class="block-note">请通过管理端知识库模块或 Supabase Storage 上传；单文件限制 10 MB，只有发布状态文档会参与顾客问答。</ion-note></ion-card-content></ion-card>
  </ion-content></ion-page>
</template>
<script setup lang="ts">
import { reactive } from 'vue'; import { onIonViewWillEnter } from '@ionic/vue'; import { IonPage,IonHeader,IonToolbar,IonButtons,IonBackButton,IonTitle,IonContent,IonCard,IonCardHeader,IonCardTitle,IonCardSubtitle,IonCardContent,IonItem,IonLabel,IonInput,IonTextarea,IonButton,IonNote,IonSelect,IonSelectOption } from '@ionic/vue'; import { storeProfile,llmConfig } from '@/services/data'; import { saveProfile,saveLlmConfig } from '@/services/store.service'; import { showToast } from '@/composables/useToast';
const profile=reactive({...storeProfile.value}); const llm=reactive({...llmConfig.value,provider:'deepseek'} as typeof llmConfig.value & {provider:string});
async function saveProfileHandler(){await saveProfile({...profile});await showToast('店铺资料已保存','success');} async function saveLlmHandler(){await saveLlmConfig({...llm,apiKey:'',timeoutMs:30000});await showToast('模型偏好已保存，服务端凭据不会写入浏览器','success');} onIonViewWillEnter(()=>{Object.assign(profile,storeProfile.value);Object.assign(llm,llmConfig.value);});
</script>
