<template>
  <ion-page><ion-header translucent><ion-toolbar><ion-buttons slot="start"><ion-back-button default-href="/tabs/more" /></ion-buttons><ion-title>店铺与服务设置</ion-title></ion-toolbar></ion-header><ion-content :fullscreen="true" class="ion-padding settings-page">
    <ion-card><ion-card-header><ion-card-title>店铺资料</ion-card-title><ion-card-subtitle>门店公开信息会显示在顾客入口。</ion-card-subtitle></ion-card-header><ion-card-content><div class="settings-grid"><ion-item><ion-label position="stacked">店铺名称</ion-label><ion-input v-model="profile.name" /></ion-item><ion-item><ion-label position="stacked">地址</ion-label><ion-input v-model="profile.address" /></ion-item><ion-item><ion-label position="stacked">联系电话</ion-label><ion-input v-model="profile.phone" /></ion-item><ion-item><ion-label position="stacked">营业时间</ion-label><ion-input v-model="profile.hours" placeholder="08:00-21:00" /></ion-item></div><ion-item><ion-label position="stacked">买家端欢迎语</ion-label><ion-textarea v-model="profile.welcome" :rows="2" /></ion-item><ion-button class="settings-save" @click="saveProfileHandler">保存店铺资料</ion-button></ion-card-content></ion-card>
    <ion-card><ion-card-header><ion-card-title>数据库连接</ion-card-title><ion-card-subtitle>{{ databaseStatus }}</ion-card-subtitle></ion-card-header><ion-card-content><ion-item><ion-label position="stacked">Supabase URL</ion-label><ion-input v-model="database.supabaseUrl" type="url" placeholder="http://127.0.0.1:54321 或 https://xxx.supabase.co" /></ion-item><ion-item><ion-label position="stacked">Anon Key</ion-label><ion-input v-model="database.supabaseAnonKey" type="password" placeholder="eyJ..." /></ion-item><ion-button class="settings-save" @click="saveDatabaseHandler">保存数据库连接</ion-button><ion-note class="block-note" color="medium">本机 Supabase 默认地址是 `http://127.0.0.1:54321`。保存后页面会刷新并重新连接。</ion-note></ion-card-content></ion-card>
    <ion-card><ion-card-header><ion-card-title>AI 服务</ion-card-title><ion-card-subtitle>填写后即可在本机直接调用 DeepSeek 或 OpenAI-compatible 接口。</ion-card-subtitle></ion-card-header><ion-card-content><div class="settings-grid"><ion-item><ion-label position="stacked">平台</ion-label><ion-select v-model="ai.aiProvider" interface="popover"><ion-select-option value="deepseek">DeepSeek</ion-select-option><ion-select-option value="openai-compatible">OpenAI-compatible</ion-select-option></ion-select></ion-item><ion-item><ion-label position="stacked">模型</ion-label><ion-input v-model="ai.aiModel" placeholder="deepseek-chat" /></ion-item></div><ion-item><ion-label position="stacked">接口地址</ion-label><ion-input v-model="ai.aiBaseUrl" placeholder="https://api.deepseek.com" /></ion-item><ion-item><ion-label position="stacked">API Key</ion-label><ion-input v-model="ai.aiApiKey" type="password" placeholder="sk-..." /></ion-item><ion-button class="settings-save" @click="saveAiHandler">保存 AI 配置</ion-button><ion-note class="block-note" color="medium">本机模式会加密存储在 Capacitor Preferences 中，不会写入代码仓库。远端生产环境建议把 Key 放在 Edge Function Secrets。</ion-note></ion-card-content></ion-card>
  </ion-content></ion-page>
</template>
<script setup lang="ts">
import { computed, reactive } from 'vue'; import { onIonViewWillEnter } from '@ionic/vue'; import { IonPage,IonHeader,IonToolbar,IonButtons,IonBackButton,IonTitle,IonContent,IonCard,IonCardHeader,IonCardTitle,IonCardSubtitle,IonCardContent,IonItem,IonLabel,IonInput,IonTextarea,IonButton,IonNote,IonSelect,IonSelectOption } from '@ionic/vue'; import { storeProfile } from '@/services/data'; import { saveProfile } from '@/services/store.service'; import { configureSupabase } from '@/lib/supabase'; import { runtimeConfig, saveRuntimeConfig } from '@/services/runtime-config.service'; import { showToast } from '@/composables/useToast';
const profile=reactive({...storeProfile.value}); const database=reactive({supabaseUrl:runtimeConfig.value.supabaseUrl,supabaseAnonKey:runtimeConfig.value.supabaseAnonKey}); const ai=reactive({...runtimeConfig.value});
const databaseStatus=computed(()=>database.supabaseUrl&&database.supabaseAnonKey?'已填写连接配置':'本地演示数据模式');
async function saveProfileHandler(){await saveProfile({...profile});await showToast('店铺资料已保存','success');}
async function saveDatabaseHandler(){await saveRuntimeConfig({supabaseUrl:database.supabaseUrl.trim(),supabaseAnonKey:database.supabaseAnonKey.trim()});await showToast('数据库连接已保存，正在刷新','success');window.setTimeout(()=>window.location.reload(),500);}
async function saveAiHandler(){await saveRuntimeConfig({aiProvider:ai.aiProvider,aiBaseUrl:ai.aiBaseUrl.trim(),aiModel:ai.aiModel.trim(),aiApiKey:ai.aiApiKey});await showToast('AI 配置已保存','success');}
onIonViewWillEnter(()=>{Object.assign(profile,storeProfile.value);Object.assign(database,{supabaseUrl:runtimeConfig.value.supabaseUrl,supabaseAnonKey:runtimeConfig.value.supabaseAnonKey});Object.assign(ai,runtimeConfig.value);configureSupabase(database.supabaseUrl,database.supabaseAnonKey);});
</script>
